# Generated by Django 5.2.14 on 2026-05-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenancerequest_caller_phone_and_more'),
        ('notifications', '0002_notificationlog_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(fields=('maintenance_request', 'purpose'), name='unique_notification_log_purpose_per_request'),
        ),
    ]
