# Generated by Django 5.2.14 on 2026-05-22 21:46

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='maintenance_phone_number',
            field=models.CharField(max_length=32, unique=True, validators=[apps.common.validators.validate_e164_phone_number]),
        ),
        migrations.AlterField(
            model_name='building',
            name='manager_phone',
            field=models.CharField(max_length=32, validators=[apps.common.validators.validate_e164_phone_number]),
        ),
        migrations.AlterField(
            model_name='building',
            name='office_phone_number',
            field=models.CharField(max_length=32, validators=[apps.common.validators.validate_e164_phone_number]),
        ),
    ]
