# Generated by Django 5.2.14 on 2026-05-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenance_request_full_name_and_issue_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='issue_type',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('water_leak', 'Water Leak'), ('drain_clog', 'Drain / Clog'), ('toilet', 'Toilet'), ('electrical', 'Electrical'), ('power_outage', 'Power Outage'), ('lighting', 'Lighting'), ('heating_cooling', 'Heating / Cooling'), ('no_heat', 'No Heat'), ('air_conditioning', 'Air Conditioning'), ('ventilation', 'Ventilation'), ('appliance', 'Appliance'), ('refrigerator', 'Refrigerator'), ('stove_oven', 'Stove / Oven'), ('dishwasher', 'Dishwasher'), ('washer_dryer', 'Washer / Dryer'), ('door_lock', 'Door / Lock'), ('window', 'Window'), ('garage_parking', 'Garage / Parking'), ('pest', 'Pest'), ('noise_security', 'Noise / Security'), ('safety_hazard', 'Safety Hazard'), ('common_area', 'Common Area'), ('exterior', 'Exterior'), ('flooring', 'Flooring'), ('walls_ceiling', 'Walls / Ceiling'), ('general_maintenance', 'General Maintenance'), ('other', 'Other')], max_length=64),
        ),
    ]
