# Generated by Django 5.2.14 on 2026-05-22 21:46

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenancerequest_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='caller_phone',
            field=models.CharField(max_length=32, validators=[apps.common.validators.validate_e164_phone_number]),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='follow_up_phone',
            field=models.CharField(blank=True, max_length=32, validators=[apps.common.validators.validate_e164_phone_number]),
        ),
    ]
